// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8qbnO_1tyqJVduECL8OK6UlZXHOpvyWo',
    appId: '1:722275017627:web:afca0ef23a04b3bc9b373e',
    messagingSenderId: '722275017627',
    projectId: 'yenitasarim-923c4',
    authDomain: 'yenitasarim-923c4.firebaseapp.com',
    storageBucket: 'yenitasarim-923c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_1aDWr-_O2rw4K0nKeuYERqT9k-wKcE',
    appId: '1:722275017627:android:5f7e884f9bae731e9b373e',
    messagingSenderId: '722275017627',
    projectId: 'yenitasarim-923c4',
    storageBucket: 'yenitasarim-923c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkiyBkAvw2b0Jsc6Q7zJFptECcEJiMEGM',
    appId: '1:722275017627:ios:8611135f80f0a7b09b373e',
    messagingSenderId: '722275017627',
    projectId: 'yenitasarim-923c4',
    storageBucket: 'yenitasarim-923c4.firebasestorage.app',
    iosBundleId: 'com.example.yeniTasarim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkiyBkAvw2b0Jsc6Q7zJFptECcEJiMEGM',
    appId: '1:722275017627:ios:8611135f80f0a7b09b373e',
    messagingSenderId: '722275017627',
    projectId: 'yenitasarim-923c4',
    storageBucket: 'yenitasarim-923c4.firebasestorage.app',
    iosBundleId: 'com.example.yeniTasarim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8qbnO_1tyqJVduECL8OK6UlZXHOpvyWo',
    appId: '1:722275017627:web:ff2e5e5ee4b52e889b373e',
    messagingSenderId: '722275017627',
    projectId: 'yenitasarim-923c4',
    authDomain: 'yenitasarim-923c4.firebaseapp.com',
    storageBucket: 'yenitasarim-923c4.firebasestorage.app',
  );
}
